---
title: "Pre Assignment - IDS 702"
author: "Altamash Rafiq, Christy Hu, Ronald Nhondova, Srishti Saha, & Tien Yu Liu"
date: "8/28/2019"
output:
  html_document:
    toc: true
    toc_depth: 4
    theme: flatly
    toc_float:
      collapsed: false
      smooth_scroll: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
h1.title {
  text-align: center;
}
h4.author {
  font-size: 15px;
  text-align: center;
}
h4.date {
  font-size: 15px;
  text-align: center;
}
</style>

## Questions

### Confidence Intervals

Decide whether the following statements are true or false. Explain your reasoning.

__Q1: For a given standard error, lower confidence levels produce wider confidence intervals.__

__Ans:__ False; they produce narrower intervals. Note that in the formula for confidence intervals (see below), the confidence level is a multiple so the lower the confidence level, the smaller the confidence interval.

$$\large \bar x \pm z\frac{s}{\sqrt{n}}$$

__Q2: If you increase sample size, the width of confidence intervals will increase.__

__Ans:__ False; the width of the confidence intervals will decrease as we will have more confidence in our point estimate due to the increased sample size. This is evident in the confidence interval formula where sample size $n$ is in the denominator.

__Q3: The statement, “the 95% confidence interval for the population mean is (350, 400)”, is equivalent to the statement, “there is a 95% probability that the population mean is between the numbers 350 and 400”.__

__Ans:__ False; from a frequentist point of view, the population parameters are fixed. Therefore, the latter statement is incorrect.

__Q4: To reduce the width of a confidence interval by roughly a factor of two (i.e. in half), you have to quadruple the sample size.__

__Ans:__ True; the denominator of the confidence interval formula fraction is $\sqrt{n}$, to double which we would need to quadrouple the sample size :-

$$\large \sqrt{4\times n} = 2\times\sqrt{n}$$

__Q5: The statement, “the 95% confidence interval for the population mean is (350, 400)” means that 95% of the population values are between 350 and 400.__

__Ans:__ False; the above statement is a statement about the population mean, not the population values.

__Q6: If you take large random samples over and over again from the same population, and make 95% confidence intervals for the population average, about 95% of the intervals should contain the population average.__

__Ans:__ True; this is as per the definition of a confidence interval assuming the population average refers to the poplation mean and not any other parameter of interest.

__Q7: If you take large random samples over and over again from the same population, and make 95% confidence intervals for the population average, about 95% of the intervals should contain the sample average.__

__Ans:__ False; all the samples will contain a sample average (sample mean) as the sample average is specific to the given sample. The 95% confidence interval produces a interval for the population mean, not the sample mean.

__Q8: When constructing a confidence interval for the population mean of a variable, it is necessary that the distribution of the variable itself follows a normal curve.__

__Ans:__ False; the variable can have any distribution. Only the sample means of random samples taken from this distribution will necessarily follow a normal distribution according to the Central Limit Theorem.

__Q9: A 95% confidence interval obtained from a random sample of 1000 people has a better chance of containing the population percentage than a 95% confidence interval obtained from a random sample of 500 people.__

__Ans:__ False; both will have the same chance of containing the population mean but both will be of different widths. 

__Q10: If you go through life making 99% confidence intervals for all sorts of population means, about 1% of the time the intervals won’t cover their respective population means.__

__Ans:__ True; this is because a large number of 99% confidence intervals implies 99% of the intervals are expected to contain their respective population means, therefore 1% of them are not expected to do so.

### Hypothesis Testing

Decide whether the following statements are true or false. Explain your reasoning.

__Q11: A p-value of .08 is more evidence against the null hypothesis than a p-value of .04.__

__Ans:__ False; the former is a higher p-value than the latter and a lower p-value is stronger evidence against the null hypothesis than a higher one.

__Q12: The statement, “the p-value is .003”, is equivalent to the statement, “there is a 0.3% probability that the null hypothesis is true”.__

__Ans:__ False; the p-value is just the probability of obtaining a point estimate as extreme or more extreme than that obtained. It does not represent the probability of the null hypothesis' being true or not.

__Q13: Even though you rejected the null hypothesis, it may still be true.__

__Ans:__ True; such a situation is known as a Type 1 Error.

__Q14: A researcher who tried to learn statistics without taking a formal course does a hypothesis test and gets a p-value of .014. He says, “there is a 98.6% chance that the alternative hypothesis is false, so the null hypothesis is true.” What, if anything, is wrong with his statement?__

__Ans:__ There are several things wrong with this statement :-

* A low p-value indicates that the null-hypothesis should be rejected, not accepted.
* We do not state whether or not a hypothesis is true or not but rather that we either accept it or fail to reject it.
* The p-value does not represent the probability that a certain hypothesis is true or not.

__Q15: You perform a hypothesis test using a sample size of four units, and you do not reject the null hypothesis. Your research colleague says this statistical test provides conclusive evidence against the alternative hypothesis. Do you agree or disagree with his conclusion? Explain your reasoning in three or less sentences.__

__Ans:__ We disagree with this conclusion for a number of reasons. Firstly, the sample size it too small for a valid hypothesis test so any conclusion has limited validity. Secondly, while a p-value does provide evidence for a certain conclusion, that conclusion is by no means conclusive and it would be incorrect to call it so.

__Q16: You are the head of the Food and Drug Administration (F.D.A.), in charge of deciding whether new drugs are effective and should be allowed to be sold to people. A pharmaceutical company trying to win approval for a new drug they manufacture claims that their drug is better than the standard drug at curing a certain disease. The company bases this claim on a study in which they gave their drug to 1000 volunteers with the disease. They compared these volunteers to a group of 1000 hospital patients who were treated with the standard drug and whose information is obtained from existing hospital records. The company found a “statistically significant” difference between the percentage of volunteers who were cured and the percentage of the comparison group who were cured. That is, they did a statistical hypothesis test and rejected the null hypothesis that the percentages are equal. As director of the F.D.A., should you permit the new drug to be sold? Explain your reasoning in three or less sentences.__

__Ans:__ While we may make the decision to permit the drug upon further evidence, this evidence is currently missing so we would not permit the drug. Firstly, we have no evidence to suggest is the 1000 volunteers in each test case were randomly chosen or if they had certain characteristics in common that may have impacted their response to the drug. Secondly, we do not know what this company defines as a statisticall significant result i.e. what p-value did they use (0.1, 0.05, 0.01 or any other?). This is problematic as a higher p-value as a measure of statistically significance requires less evidence of difference between the two drugs' performance to reject the null hypothesis. Thirdly, while the company does state the difference is statistically significant, it does not state if it is scientifically significant i.e. the difference between the performances of the drugs is significant enough to warrant a change. While this, in and of itself, should not warrant the drug not being permitted, it is worth considering as a criteria given that it is being marketted as a better drug than the standard drug. Finally, the drug company conducted a two-sided t-test when the problem actually demands a one-sided t-test. Therefore, their result is currently invalid.

__Q17: If you get a p-value of .13, it means there is a 13% chance that the sample average equals the population average.__

__Ans:__ False; the p-value is the probability of getting a point estimate as extreme or more extreme than that obtained. It does not give the probability of equality between the sample average and the population average.

__Q18: If you get a p-value of .13, it means there is a 13% chance that the sample average does not equal the population average.__

__Ans:__ False; the p-value is not the probability of equality between a sample and population statistic. It is instead the probability of getting a point estimate as extreme or more extreme than that obtained.

__Q19: If you get a p-value of .13, it means there is an 87% chance that the sample average equals the population average.__

__Ans:__ False; the p-value does not represent the probability of equality between the sample average and the population average.

__Q20: If you get a p-value of .13, it means there is an 87% chance that the sample average does not equal the population average.__

__Ans:__ False; the p-value does not represent the probability of equality or inequality between the sample average and the population average.

__Q21: If you get a p-value of .13, it means that the null hypothesis is true in 13% of all samples.__

__Ans:__ False; the p-value is not a statement about the probability of correctness of a null hypothesis. 

__Q22: If you get a p-value of .13, it means that when the null hypothesis is true, a value of the test statistic as or more extreme than what was observed occurs in about 13% of all samples.__

__Ans:__ True; this is as per the definition of a p-value.






